import type { IFlight } from "../../types/flight.types";

export const FLIGHTS: IFlight[] = [
  {
    logo: "/logos/turkish.svg",
    id: "TK143",
    airline: {
      name: "Turkish Airlines",
      country: "Turkey",
    },
    aircraftReg: "TC-JFP",
    from: {
      city: "Sofia",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "SOF",
      coordinates: [42.6977, 23.3219],
    },
    to: {
      city: "Beijing",
      country: "China",
      countryCode: "CN",
      timezone: "UTC +8",
      code: "PEK",
      coordinates: [39.9042, 116.4074],
    },
    airplane: {
      image: "/planes/turkish.png",
      name: "Airbus A330",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 870,
      altitude: 10600,
    },
    progress: 75,
    currentLocation: {
      coordinates: [41.30095, 69.86465],
    },
  },
  {
    logo: "/logos/ryanair.svg",
    id: "RN1782",
    airline: {
      name: "Ryanair",
      country: "Ireland",
    },
    aircraftReg: "D-AISP",
    from: {
      city: "Dublin",
      country: "Ireland",
      countryCode: "IE",
      timezone: "UTC +1",
      code: "DUB",
      coordinates: [53.4213, -6.2701],
    },
    to: {
      city: "Larnaca",
      country: "Cyprus",
      countryCode: "CY",
      timezone: "UTC +3",
      code: "LCA",
      coordinates: [34.8751, 33.6249],
    },
    airplane: {
      image: "/planes/ryanair.png",
      name: "Boeing 737-800",
    },
    colorGradient: ["#A3C1E0", "#D1E4F7"],
    route: {
      speed: 840,
      altitude: 11200,
    },
    progress: 95,
    currentLocation: {
      coordinates: [44.1482, 13.6774],
    },
  },
  {
    logo: "/logos/s7.svg",
    id: "S7124",
    airline: {
      name: "S7 Airlines",
      country: "Russia",
    },
    aircraftReg: "RA-73415",
    from: {
      city: "Nice",
      country: "France",
      countryCode: "FR",
      timezone: "UTC +2",
      code: "NCE",
      coordinates: [43.6653, 7.215],
    },
    to: {
      city: "Tbilisi",
      country: "Georgia",
      countryCode: "GE",
      timezone: "UTC +4",
      code: "TBS",
      coordinates: [41.6692, 44.9547],
    },
    airplane: {
      image: "/planes/s7.png",
      name: "Airbus A320neo",
    },
    colorGradient: ["#D1F8C4", "#E8FFE2"],
    route: {
      speed: 860,
      altitude: 10900,
    },
    progress: 10,
    currentLocation: {
      coordinates: [42.66725, 26.08485],
    },
  },
  {
    logo: "/logos/swiss.svg",
    id: "LX318",
    airline: {
      name: "SWISS IAL",
      country: "Switzerland",
    },
    aircraftReg: "HB-JHK",
    from: {
      city: "Porto",
      country: "Portugal",
      countryCode: "PT",
      timezone: "UTC +1",
      code: "OPO",
      coordinates: [41.2481, -8.6814],
    },
    to: {
      city: "Baku",
      country: "Azerbaijan",
      countryCode: "AZ",
      timezone: "UTC +4",
      code: "GYD",
      coordinates: [40.4675, 50.0467],
    },
    airplane: {
      image: "/planes/swiss.png",
      name: "Airbus A220-300",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 830,
      altitude: 10700,
    },
    progress: 55,
    currentLocation: {
      coordinates: [40.8578, 20.68265],
    },
  },
  {
    logo: "/logos/lufthansa.svg",
    id: "LH401",
    airline: {
      name: "Lufthansa",
      country: "Germany",
    },
    aircraftReg: "D-AIXD",
    from: {
      city: "Burgas",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "BOJ",
      coordinates: [42.5696, 27.5152],
    },
    to: {
      city: "Muscat",
      country: "Oman",
      countryCode: "OM",
      timezone: "UTC +4",
      code: "MCT",
      coordinates: [23.5933, 58.2844],
    },
    airplane: {
      image: "/planes/lufthansa.png",
      name: "Airbus A350-900",
    },
    colorGradient: ["#A8C6E6", "#DCE6F7"],
    route: {
      speed: 890,
      altitude: 11300,
    },
    progress: 25,
    currentLocation: {
      coordinates: [33.08145, 42.8998],
    },
  },
  // Перемешанные рейсы (индексы 5–29)
  {
    logo: "/logos/swiss.svg",
    id: "LX641",
    airline: {
      name: "SWISS IAL",
      country: "Switzerland",
    },
    aircraftReg: "HB-JKN",
    from: {
      city: "Sofia",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "SOF",
      coordinates: [42.6977, 23.3219],
    },
    to: {
      city: "Zurich",
      country: "Switzerland",
      countryCode: "CH",
      timezone: "UTC +2",
      code: "ZRH",
      coordinates: [47.4647, 8.5492],
    },
    airplane: {
      image: "/planes/swiss.png",
      name: "Airbus A220-300",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 820,
      altitude: 10500,
    },
    progress: 80,
    currentLocation: {
      coordinates: [45.0812, 13.93555],
    },
  },
  {
    logo: "/logos/ryanair.svg",
    id: "RN3156",
    airline: {
      name: "Ryanair",
      country: "Ireland",
    },
    aircraftReg: "D-AKUS",
    from: {
      city: "Cork",
      country: "Ireland",
      countryCode: "IE",
      timezone: "UTC +1",
      code: "ORK",
      coordinates: [51.8413, -8.4911],
    },
    to: {
      city: "Rome",
      country: "Italy",
      countryCode: "IT",
      timezone: "UTC +2",
      code: "FCO",
      coordinates: [41.8003, 12.2551],
    },
    airplane: {
      image: "/planes/ryanair.png",
      name: "Boeing 737-800",
    },
    colorGradient: ["#A3C1E0", "#D1E4F7"],
    route: {
      speed: 820,
      altitude: 11100,
    },
    progress: 30,
    currentLocation: {
      coordinates: [48.8209, 0.3821],
    },
  },
  {
    logo: "/logos/lufthansa.svg",
    id: "LH845",
    airline: {
      name: "Lufthansa",
      country: "Germany",
    },
    aircraftReg: "D-AKBH",
    from: {
      city: "Paris",
      country: "France",
      countryCode: "FR",
      timezone: "UTC +2",
      code: "CDG",
      coordinates: [49.0097, 2.5478],
    },
    to: {
      city: "Singapore",
      country: "Singapore",
      countryCode: "SG",
      timezone: "UTC +8",
      code: "SIN",
      coordinates: [1.3644, 103.9915],
    },
    airplane: {
      image: "/planes/lufthansa.png",
      name: "Airbus A350-900",
    },
    colorGradient: ["#A8C6E6", "#DCE6F7"],
    route: {
      speed: 900,
      altitude: 11300,
    },
    progress: 40,
    currentLocation: {
      coordinates: [35.18705, 53.26965],
    },
  },
  {
    logo: "/logos/turkish.svg",
    id: "TK512",
    airline: {
      name: "Turkish Airlines",
      country: "Turkey",
    },
    aircraftReg: "TC-JKT",
    from: {
      city: "Paris",
      country: "France",
      countryCode: "FR",
      timezone: "UTC +2",
      code: "CDG",
      coordinates: [49.0097, 2.5478],
    },
    to: {
      city: "Istanbul",
      country: "Turkey",
      countryCode: "TR",
      timezone: "UTC +3",
      code: "IST",
      coordinates: [41.2753, 28.7519],
    },
    airplane: {
      image: "/planes/turkish.png",
      name: "Airbus A330",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 850,
      altitude: 10400,
    },
    progress: 80,
    currentLocation: {
      coordinates: [43.22274, 22.15138],
    },
  },
  {
    logo: "/logos/s7.svg",
    id: "S7568",
    airline: {
      name: "S7 Airlines",
      country: "Russia",
    },
    aircraftReg: "RA-73459",
    from: {
      city: "Paris",
      country: "France",
      countryCode: "FR",
      timezone: "UTC +2",
      code: "CDG",
      coordinates: [49.0097, 2.5478],
    },
    to: {
      city: "Astana",
      country: "Kazakhstan",
      countryCode: "KZ",
      timezone: "UTC +6",
      code: "NQZ",
      coordinates: [51.0221, 71.4669],
    },
    airplane: {
      image: "/planes/s7.png",
      name: "Airbus A320neo",
    },
    colorGradient: ["#D1F8C4", "#E8FFE2"],
    route: {
      speed: 880,
      altitude: 11000,
    },
    progress: 55,
    currentLocation: {
      coordinates: [48.5159, 37.00735],
    },
  },
  {
    logo: "/logos/swiss.svg",
    id: "LX429",
    airline: {
      name: "SWISS IAL",
      country: "Switzerland",
    },
    aircraftReg: "HB-JIL",
    from: {
      city: "Zurich",
      country: "Switzerland",
      countryCode: "CH",
      timezone: "UTC +2",
      code: "ZRH",
      coordinates: [47.4647, 8.5492],
    },
    to: {
      city: "New York",
      country: "United States",
      countryCode: "US",
      timezone: "UTC -4",
      code: "JFK",
      coordinates: [40.6413, -73.7781],
    },
    airplane: {
      image: "/planes/swiss.png",
      name: "Airbus A220-300",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 840,
      altitude: 10600,
    },
    progress: 50,
    currentLocation: {
      coordinates: [47.05295, -32.66365],
    },
  },
  {
    logo: "/logos/ryanair.svg",
    id: "RN6489",
    airline: {
      name: "Ryanair",
      country: "Ireland",
    },
    aircraftReg: "D-ANYZ",
    from: {
      city: "Lisbon",
      country: "Portugal",
      countryCode: "PT",
      timezone: "UTC +1",
      code: "LIS",
      coordinates: [38.7813, -9.1359],
    },
    to: {
      city: "Berlin",
      country: "Germany",
      countryCode: "DE",
      timezone: "UTC +2",
      code: "BER",
      coordinates: [52.5597, 13.2877],
    },
    airplane: {
      image: "/planes/ryanair.png",
      name: "Boeing 737-800",
    },
    colorGradient: ["#A3C1E0", "#D1E4F7"],
    route: {
      speed: 830,
      altitude: 11000,
    },
    progress: 85,
    currentLocation: {
      coordinates: [47.1705, 2.0759],
    },
  },
  {
    logo: "/logos/lufthansa.svg",
    id: "LH623",
    airline: {
      name: "Lufthansa",
      country: "Germany",
    },
    aircraftReg: "D-AIZF",
    from: {
      city: "Munich",
      country: "Germany",
      countryCode: "DE",
      timezone: "UTC +2",
      code: "MUC",
      coordinates: [48.3538, 11.7861],
    },
    to: {
      city: "Erevan",
      country: "Armenia",
      countryCode: "AM",
      timezone: "UTC +4",
      code: "ARM",
      coordinates: [40.1675, 44.5467],
    },
    airplane: {
      image: "/planes/lufthansa.png",
      name: "Airbus A350-900",
    },
    colorGradient: ["#A8C6E6", "#DCE6F7"],
    route: {
      speed: 890,
      altitude: 11100,
    },
    progress: 60,
    currentLocation: {
      coordinates: [43.41065, 30.9164],
    },
  },
  {
    logo: "/logos/turkish.svg",
    id: "TK201",
    airline: {
      name: "Turkish Airlines",
      country: "Turkey",
    },
    aircraftReg: "TC-JGQ",
    from: {
      city: "Istanbul",
      country: "Turkey",
      countryCode: "TR",
      timezone: "UTC +3",
      code: "IST",
      coordinates: [41.2753, 28.7519],
    },
    to: {
      city: "Dubai",
      country: "United Arab Emirates",
      countryCode: "AE",
      timezone: "UTC +4",
      code: "DXB",
      coordinates: [25.2528, 55.3644],
    },
    airplane: {
      image: "/planes/turkish.png",
      name: "Airbus A330",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 880,
      altitude: 10500,
    },
    progress: 40,
    currentLocation: {
      coordinates: [31.76405, 39.05815],
    },
  },
  {
    logo: "/logos/s7.svg",
    id: "S7235",
    airline: {
      name: "S7 Airlines",
      country: "Russia",
    },
    aircraftReg: "RA-73426",
    from: {
      city: "Moscow",
      country: "Russia",
      countryCode: "RU",
      timezone: "UTC +3",
      code: "SVO",
      coordinates: [55.9726, 37.4146],
    },
    to: {
      city: "Dubai",
      country: "United Arab Emirates",
      countryCode: "AE",
      timezone: "UTC +4",
      code: "DXB",
      coordinates: [25.2528, 55.3644],
    },
    airplane: {
      image: "/planes/s7.png",
      name: "Airbus A320neo",
    },
    colorGradient: ["#D1F8C4", "#E8FFE2"],
    route: {
      speed: 860,
      altitude: 10800,
    },
    progress: 35,
    currentLocation: {
      coordinates: [40.6127, 46.3895],
    },
  },
  {
    logo: "/logos/swiss.svg",
    id: "LX863",
    airline: {
      name: "SWISS IAL",
      country: "Switzerland",
    },
    aircraftReg: "HB-JMP",
    from: {
      city: "Dublin",
      country: "Ireland",
      countryCode: "IE",
      timezone: "UTC +1",
      code: "DUB",
      coordinates: [53.4213, -6.2701],
    },
    to: {
      city: "Geneva",
      country: "Switzerland",
      countryCode: "CH",
      timezone: "UTC +2",
      code: "GVA",
      coordinates: [46.2381, 6.1089],
    },
    airplane: {
      image: "/planes/swiss.png",
      name: "Airbus A220-300",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 840,
      altitude: 10600,
    },
    progress: 70,
    currentLocation: {
      coordinates: [49.8297, -0.0806],
    },
  },
  {
    logo: "/logos/ryanair.svg",
    id: "RN2045",
    airline: {
      name: "Ryanair",
      country: "Ireland",
    },
    aircraftReg: "D-AJTR",
    from: {
      city: "Dublin",
      country: "Ireland",
      countryCode: "IE",
      timezone: "UTC +1",
      code: "DUB",
      coordinates: [53.4213, -6.2701],
    },
    to: {
      city: "Barcelona",
      country: "Spain",
      countryCode: "ES",
      timezone: "UTC +2",
      code: "BCN",
      coordinates: [41.2971, 2.0785],
    },
    airplane: {
      image: "/planes/ryanair.png",
      name: "Boeing 737-800",
    },
    colorGradient: ["#A3C1E0", "#D1E4F7"],
    route: {
      speed: 830,
      altitude: 11000,
    },
    progress: 70,
    currentLocation: {
      coordinates: [46.1592, -0.6957],
    },
  },
  {
    logo: "/logos/lufthansa.svg",
    id: "LH512",
    airline: {
      name: "Lufthansa",
      country: "Germany",
    },
    aircraftReg: "D-AIYE",
    from: {
      city: "Frankfurt",
      country: "Germany",
      countryCode: "DE",
      timezone: "UTC +2",
      code: "FRA",
      coordinates: [50.0264, 8.5431],
    },
    to: {
      city: "Shanghai",
      country: "China",
      countryCode: "CN",
      timezone: "UTC +8",
      code: "PVG",
      coordinates: [31.1434, 121.8052],
    },
    airplane: {
      image: "/planes/lufthansa.png",
      name: "Airbus A350-900",
    },
    colorGradient: ["#A8C6E6", "#DCE6F7"],
    route: {
      speed: 900,
      altitude: 11200,
    },
    progress: 30,
    currentLocation: {
      coordinates: [40.5849, 49.17415],
    },
  },
  {
    logo: "/logos/turkish.svg",
    id: "TK617",
    airline: {
      name: "Turkish Airlines",
      country: "Turkey",
    },
    aircraftReg: "TC-JLU",
    from: {
      city: "Lisbon",
      country: "Portugal",
      countryCode: "PT",
      timezone: "UTC +1",
      code: "LIS",
      coordinates: [38.7813, -9.1359],
    },
    to: {
      city: "Cairo",
      country: "Egypt",
      countryCode: "EG",
      timezone: "UTC +2",
      code: "CAI",
      coordinates: [30.0444, 31.2357],
    },
    airplane: {
      image: "/planes/turkish.png",
      name: "Airbus A330",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 870,
      altitude: 10600,
    },
    progress: 50,
    currentLocation: {
      coordinates: [39.41285, 11.0499],
    },
  },
  {
    logo: "/logos/s7.svg",
    id: "S7346",
    airline: {
      name: "S7 Airlines",
      country: "Russia",
    },
    aircraftReg: "RA-73437",
    from: {
      city: "St. Petersburg",
      country: "Russia",
      countryCode: "RU",
      timezone: "UTC +3",
      code: "LED",
      coordinates: [59.8003, 30.2625],
    },
    to: {
      city: "Tbilisi",
      country: "Georgia",
      countryCode: "GE",
      timezone: "UTC +4",
      code: "TBS",
      coordinates: [41.6692, 44.9547],
    },
    airplane: {
      image: "/planes/s7.png",
      name: "Airbus A320neo",
    },
    colorGradient: ["#D1F8C4", "#E8FFE2"],
    route: {
      speed: 850,
      altitude: 10700,
    },
    progress: 60,
    currentLocation: {
      coordinates: [48.73475, 37.6086],
    },
  },
  {
    logo: "/logos/swiss.svg",
    id: "LX530",
    airline: {
      name: "SWISS IAL",
      country: "Switzerland",
    },
    aircraftReg: "HB-JJM",
    from: {
      city: "Geneva",
      country: "Switzerland",
      countryCode: "CH",
      timezone: "UTC +2",
      code: "GVA",
      coordinates: [46.2381, 6.1089],
    },
    to: {
      city: "Istanbul",
      country: "Turkey",
      countryCode: "TR",
      timezone: "UTC +3",
      code: "IST",
      coordinates: [41.2753, 28.7519],
    },
    airplane: {
      image: "/planes/swiss.png",
      name: "Airbus A220-300",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 830,
      altitude: 10700,
    },
    progress: 65,
    currentLocation: {
      coordinates: [42.7567, 17.4304],
    },
  },
  {
    logo: "/logos/ryanair.svg",
    id: "RN5378",
    airline: {
      name: "Ryanair",
      country: "Ireland",
    },
    aircraftReg: "D-AMWX",
    from: {
      city: "Paris",
      country: "France",
      countryCode: "FR",
      timezone: "UTC +2",
      code: "CDG",
      coordinates: [49.0097, 2.5478],
    },
    to: {
      city: "Athens",
      country: "Greece",
      countryCode: "GR",
      timezone: "UTC +3",
      code: "ATH",
      coordinates: [37.9364, 23.9472],
    },
    airplane: {
      image: "/planes/ryanair.png",
      name: "Boeing 737-800",
    },
    colorGradient: ["#A3C1E0", "#D1E4F7"],
    route: {
      speed: 840,
      altitude: 11200,
    },
    progress: 45,
    currentLocation: {
      coordinates: [43.47305, 13.2475],
    },
  },
  {
    logo: "/logos/lufthansa.svg",
    id: "LH956",
    airline: {
      name: "Lufthansa",
      country: "Germany",
    },
    aircraftReg: "D-ALCI",
    from: {
      city: "Dublin",
      country: "Ireland",
      countryCode: "IE",
      timezone: "UTC +1",
      code: "DUB",
      coordinates: [53.4213, -6.2701],
    },
    to: {
      city: "Munich",
      country: "Germany",
      countryCode: "DE",
      timezone: "UTC +2",
      code: "MUC",
      coordinates: [48.3538, 11.7861],
    },
    airplane: {
      image: "/planes/lufthansa.png",
      name: "Airbus A350-900",
    },
    colorGradient: ["#A8C6E6", "#DCE6F7"],
    route: {
      speed: 890,
      altitude: 11200,
    },
    progress: 55,
    currentLocation: {
      coordinates: [50.38755, 2.758],
    },
  },
  {
    logo: "/logos/turkish.svg",
    id: "TK305",
    airline: {
      name: "Turkish Airlines",
      country: "Turkey",
    },
    aircraftReg: "TC-JHR",
    from: {
      city: "Ankara",
      country: "Turkey",
      countryCode: "TR",
      timezone: "UTC +3",
      code: "ESB",
      coordinates: [40.1281, 32.9951],
    },
    to: {
      city: "Moscow",
      country: "Russia",
      countryCode: "RU",
      timezone: "UTC +3",
      code: "SVO",
      coordinates: [55.9726, 37.4146],
    },
    airplane: {
      image: "/planes/turkish.png",
      name: "Airbus A330",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 860,
      altitude: 10800,
    },
    progress: 60,
    currentLocation: {
      coordinates: [46.05035, 35.20485],
    },
  },
  {
    logo: "/logos/s7.svg",
    id: "S7679",
    airline: {
      name: "S7 Airlines",
      country: "Russia",
    },
    aircraftReg: "RA-73460",
    from: {
      city: "Lisbon",
      country: "Portugal",
      countryCode: "PT",
      timezone: "UTC +1",
      code: "LIS",
      coordinates: [38.7813, -9.1359],
    },
    to: {
      city: "Moscow",
      country: "Russia",
      countryCode: "RU",
      timezone: "UTC +3",
      code: "SVO",
      coordinates: [55.9726, 37.4146],
    },
    airplane: {
      image: "/planes/s7.png",
      name: "Airbus A320neo",
    },
    colorGradient: ["#D1F8C4", "#E8FFE2"],
    route: {
      speed: 860,
      altitude: 10800,
    },
    progress: 75,
    currentLocation: {
      coordinates: [48.37695, 14.13935],
    },
  },
  {
    logo: "/logos/swiss.svg",
    id: "LX752",
    airline: {
      name: "SWISS IAL",
      country: "Switzerland",
    },
    aircraftReg: "HB-JLO",
    from: {
      city: "Paris",
      country: "France",
      countryCode: "FR",
      timezone: "UTC +2",
      code: "CDG",
      coordinates: [49.0097, 2.5478],
    },
    to: {
      city: "Lisbon",
      country: "Portugal",
      countryCode: "PT",
      timezone: "UTC +1",
      code: "LIS",
      coordinates: [38.7813, -9.1359],
    },
    airplane: {
      image: "/planes/swiss.png",
      name: "Airbus A220-300",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 830,
      altitude: 10800,
    },
    progress: 45,
    currentLocation: {
      coordinates: [43.8955, -3.29405],
    },
  },
  {
    logo: "/logos/ryanair.svg",
    id: "RN4267",
    airline: {
      name: "Ryanair",
      country: "Ireland",
    },
    aircraftReg: "D-ALVT",
    from: {
      city: "Sofia",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "SOF",
      coordinates: [42.6977, 23.3219],
    },
    to: {
      city: "London",
      country: "United Kingdom",
      countryCode: "UK",
      timezone: "UTC +1",
      code: "STN",
      coordinates: [51.885, 0.235],
    },
    airplane: {
      image: "/planes/ryanair.png",
      name: "Boeing 737-800",
    },
    colorGradient: ["#A3C1E0", "#D1E4F7"],
    route: {
      speed: 850,
      altitude: 10900,
    },
    progress: 65,
    currentLocation: {
      coordinates: [46.29145, 14.27845],
    },
  },
  {
    logo: "/logos/lufthansa.svg",
    id: "LH734",
    airline: {
      name: "Lufthansa",
      country: "Germany",
    },
    aircraftReg: "D-AJAG",
    from: {
      city: "Sofia",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "SOF",
      coordinates: [42.6977, 23.3219],
    },
    to: {
      city: "Frankfurt",
      country: "Germany",
      countryCode: "DE",
      timezone: "UTC +2",
      code: "FRA",
      coordinates: [50.0264, 8.5431],
    },
    airplane: {
      image: "/planes/lufthansa.png",
      name: "Airbus A350-900",
    },
    colorGradient: ["#A8C6E6", "#DCE6F7"],
    route: {
      speed: 880,
      altitude: 11000,
    },
    progress: 75,
    currentLocation: {
      coordinates: [46.36205, 15.9325],
    },
  },
  {
    logo: "/logos/turkish.svg",
    id: "TK409",
    airline: {
      name: "Turkish Airlines",
      country: "Turkey",
    },
    aircraftReg: "TC-JIS",
    from: {
      city: "Sofia",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "SOF",
      coordinates: [42.6977, 23.3219],
    },
    to: {
      city: "Tokyo",
      country: "Japan",
      countryCode: "JP",
      timezone: "UTC +9",
      code: "NRT",
      coordinates: [35.7647, 140.3863],
    },
    airplane: {
      image: "/planes/turkish.png",
      name: "Airbus A330",
    },
    colorGradient: ["#F4A3A3", "#FFD6D6"],
    route: {
      speed: 900,
      altitude: 11000,
    },
    progress: 20,
    currentLocation: {
      coordinates: [41.23114, 39.98146],
    },
  },
  {
    logo: "/logos/s7.svg",
    id: "S7457",
    airline: {
      name: "S7 Airlines",
      country: "Russia",
    },
    aircraftReg: "RA-73448",
    from: {
      city: "Sofia",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "SOF",
      coordinates: [42.6977, 23.3219],
    },
    to: {
      city: "Yerevan",
      country: "Armenia",
      countryCode: "AM",
      timezone: "UTC +4",
      code: "EVN",
      coordinates: [40.1472, 44.3959],
    },
    airplane: {
      image: "/planes/s7.png",
      name: "Airbus A320neo",
    },
    colorGradient: ["#D1F8C4", "#E8FFE2"],
    route: {
      speed: 870,
      altitude: 10900,
    },
    progress: 25,
    currentLocation: {
      coordinates: [41.42245, 30.85895],
    },
  },
];
